title: "Amy Zhang" 
description: ""
logo: "/assets/img/your-circular-photo-2.png"  # <- Update this filename when you upload your photo
github_username: "amyzhang-commits"
linkedin_username: "azhang2262"
email: "amy.appearouette@gmail.com"  # <- This will display exactly as written
theme: jekyll-theme-minimal
