title: "Amy Zhang" 
description: "Data Analyst; emerging Data Scientist"
logo: "/assets/img/your-circular-photo-2.png"  # <- Update this filename when you upload your photo
github_username: "amyzhang-commits"
linkedin_username: "azhang2262"
email: "[forthcoming]"  # <- This will display exactly as written
theme: jekyll-theme-minimal
